---

- name: Installing base packages
  apt:
    update_cache: yes
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - python-apt
    - dnsutils
    - jq
    - unzip
    - curl

- name: Download the checksum value
  get_url:
    url: "{{ checksum_url }}"
    dest: /tmp/consul-{{ consul_version }}_SHA256SUMS

- name: Register the checksum value
  shell: /bin/cat /tmp/consul-{{ consul_version }}_SHA256SUMS | grep linux_amd64.zip | awk '{ print $1 }'
  register: consul_checksum_value

- name: Download consul
  get_url:
    url: "{{ consul_url }}"
    dest: /tmp/consul-{{ consul_version }}.zip
    checksum: sha256:{{ consul_checksum_value.stdout }}

- name: Unzip consul agent and move to /usr/local/bin/
  unarchive:
    src: /tmp/consul-{{ consul_version }}.zip
    dest: /usr/local/bin/
    remote_src: yes

- name: Change ownership to root
  file:
    path: /usr/local/bin/consul
    owner: root
    group: root
    mode: u+x

- name: Install autocomplete for consul
  shell: complete -C /usr/local/bin/consul consul
  args:
    executable: /bin/bash

- name: Create consul user
  user:
    name: consul
    system: yes
    shell: /bin/false
    home: /etc/consul.d

- name: create consul data directory
  file:
    path: "{{consul_data_dir}}"
    state: directory
    owner: consul
    group: consul

- name : create consul config directory
  file:
    path: "{{consul_config_dir}}"
    state: directory
    owner: consul
    group: consul

- name: Copy consul config file
  template:
    src: config.json.j2
    dest: "{{ consul_config_file }}"
    owner: consul
    group: consul
    mode: 0640

- name: Copy systemd service file
  template:
    src: consul.service.j2
    dest: /etc/systemd/system/consul.service
    owner: root
    group: root
    mode: 0644

- name: Restart service
  systemd:
    name: consul
    enabled: yes
    daemon_reload: yes
    state: restarted
  # notify:
  #   - "reload systemd"
  #   - "restart consul"